### ISSUE TITLE
添加规则订阅时，gfwlist.txt无法更新

### ISSUE THREAD

**Issue by yaoyansi** [liruqi/west-chamber-season-3#110]
我按照这里的教程http://wcproxy.sinaapp.com/how.html
在“添加规则订阅”步骤里，选择https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt,
显示：“状态：自动更新；最后下载：XXXXX(失败，下载错误)”
我发现https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt 这个文件根本无法访问

**Comment by vton** [comment]
我这里可以访问 https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt （代理访问，直接访问不行），但更新情景模式依然是失败。

**Comment by liruqi** [comment]
这个客户端我已经不维护了。
需要的话，可以用这个公共代理 http://liruqi.github.io/jjproxy/
